# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Yarne/FPGA_PROJECT/FPGA_project_final_solution/FPGA_project_group4/FPGA_project_group4.srcs/sources_1/bd/design_1/ip/design_1_RAM_4M_0_0/design_1_RAM_4M_0_0.xci
# IP: The module: 'design_1_RAM_4M_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Yarne/FPGA_PROJECT/FPGA_project_final_solution/FPGA_project_group4/FPGA_project_group4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Yarne/FPGA_PROJECT/FPGA_project_final_solution/FPGA_project_group4/FPGA_project_group4.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: C:/Users/Yarne/FPGA_PROJECT/FPGA_project_final_solution/FPGA_project_group4/FPGA_project_group4.srcs/sources_1/bd/design_1/ip/design_1_RAM_4M_0_0/design_1_RAM_4M_0_0.xci
# IP: The module: 'design_1_RAM_4M_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Yarne/FPGA_PROJECT/FPGA_project_final_solution/FPGA_project_group4/FPGA_project_group4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Yarne/FPGA_PROJECT/FPGA_project_final_solution/FPGA_project_group4/FPGA_project_group4.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
